import React from "react";

export const Options = () => {
  return (
    <>
      <option value="default">-- Choose Currency --</option>
      <option value="USD">United States Dollar</option>
      <option value="AED">United Arab Emirates Dirham</option>
      <option value="AFN">Afghan Afghani</option>
      <option value="ALL">Albanian Lek</option>
      <option value="AMD">Armenian Dram</option>
      <option value="ANG">Netherlands Antillean Guilder</option>
      <option value="AOA">Angolan Kwanza</option>
      <option value="ARS">Argentine Peso</option>
      <option value="AUD">Australian Dollar</option>
      <option value="AWG">Aruban Florin</option>
      <option value="AZN">Azerbaijani Manat</option>
      <option value="BAM">Bosnia and Herzegovina Convertible Mark</option>
      <option value="BBD">Barbadian or Bajan Dollar</option>
      <option value="BDT">Bangladeshi Taka</option>
      <option value="BGN">Bulgarian Lev</option>
      <option value="BHD">Bahraini Dinar</option>
      <option value="BIF">Burundian Franc</option>
      <option value="BMD">Bermudian Dollar</option>
      <option value="BND">Bruneian Dollar</option>
      <option value="BOB">Bolivian Bolíviano</option>
      <option value="BRL">Brazilian Real</option>
      <option value="BSD">Bahamian Dollar</option>
      <option value="BTN">Bhutanese Ngultrum</option>
      <option value="BWP">Botswana Pula</option>
      <option value="BYN">Belarusian Ruble</option>
      <option value="BZD">Belizean Dollar</option>
      <option value="CAD">Canadian Dollar</option>
      <option value="CDF">Congolese Franc</option>
      <option value="CHF">Swiss Franc</option>
      <option value="CLP">Chilean Peso</option>
      <option value="CNY">Chinese Yuan Renminbi</option>
      <option value="COP">Colombian Peso</option>
      <option value="CRC">Costa Rican Colon</option>
      <option value="CUP">Cuban Peso</option>
      <option value="CVE">Cape Verdean Escudo</option>
      <option value="CZK">Czech Koruna</option>
      <option value="DJF">Djiboutian Franc</option>
      <option value="DKK">Danish Krone</option>
      <option value="DOP">Dominican Peso</option>
      <option value="DZD">Algerian Dinar</option>
      <option value="EGP">Egyptian Pound</option>
      <option value="ERN">Eritrean Nakfa</option>
      <option value="ETB">Ethiopian Birr</option>
      <option value="EUR">Euro</option>
      <option value="FJD">Fijian Dollar</option>
      <option value="GBP">British Pound</option>
      <option value="GEL">Georgian Lari</option>
      <option value="GHS">Ghanaian Cedi</option>
      <option value="GIP">Gibraltar Pound</option>
      <option value="GMD">Gambian Dalasi</option>
      <option value="GNF">Guinean Franc</option>
      <option value="GTQ">Guatemalan Quetzal</option>
      <option value="GYD">Guyanese Dollar</option>
      <option value="HKD">Hong Kong Dollar</option>
      <option value="HNL">Honduran Lempira</option>
      <option value="HRK">Croatian Kuna</option>
      <option value="HTG">Haitian Gourde</option>
      <option value="HUF">Hungarian Forint</option>
      <option value="IDR">Indonesian Rupiah</option>
      <option value="ILS">Israeli Shekel</option>
      <option value="INR">Indian Rupee</option>
      <option value="IQD">Iraqi Dinar</option>
      <option value="IRR">Iranian Rial</option>
      <option value="ISK">Icelandic Krona</option>
      <option value="JMD">Jamaican Dollar</option>
      <option value="JOD">Jordanian Dinar</option>
      <option value="JPY">Japanese Yen</option>
      <option value="KES">Kenyan Shilling</option>
      <option value="KGS">Kyrgyzstani Som</option>
      <option value="KHR">Cambodian Riel</option>
      <option value="KMF">Comorian Franc</option>
      <option value="KRW">South Korean Won</option>
      <option value="KWD">Kuwaiti Dinar</option>
      <option value="KYD">Caymanian Dollar</option>
      <option value="KZT">Kazakhstani Tenge</option>
      <option value="LAK">Lao or Laotian Kip</option>
      <option value="LBP">Lebanese Pound</option>
      <option value="LKR">Sri Lankan Rupee</option>
      <option value="LRD">Liberian Dollar</option>
      <option value="LSL">Basotho Loti</option>
      <option value="LYD">Libyan Dinar</option>
      <option value="MAD">Moroccan Dirham</option>
      <option value="MDL">Moldovan Leu</option>
      <option value="MGA">Malagasy Ariary</option>
      <option value="MKD">Macedonian Denar</option>
      <option value="MMK">Burmese Kyat</option>
      <option value="MNT">Mongolian Tughrik</option>
      <option value="MOP">Macau Pataca</option>
      <option value="MRU">Mauritanian Ouguiya</option>
      <option value="MUR">Mauritian Rupee</option>
      <option value="MVR">Maldivian Rufiyaa</option>
      <option value="MWK">Malawian Kwacha</option>
      <option value="MXN">Mexican Peso</option>
      <option value="MYR">Malaysian Ringgit</option>
      <option value="MZN">Mozambican Metical</option>
      <option value="NAD">Namibian Dollar</option>
      <option value="NGN">Nigerian Naira</option>
      <option value="NIO">Nicaraguan Cordoba</option>
      <option value="NOK">Norwegian Krone</option>
      <option value="NPR">Nepalese Rupee</option>
      <option value="NZD">New Zealand Dollar</option>
      <option value="OMR">Omani Rial</option>
      <option value="PAB">Panamanian Balboa</option>
      <option value="PEN">Peruvian Sol</option>
      <option value="PGK">Papua New Guinean Kina</option>
      <option value="PHP">Philippine Peso</option>
      <option value="PKR">Pakistani Rupee</option>
      <option value="PLN">Polish Zloty</option>
      <option value="PYG">Paraguayan Guarani</option>
      <option value="QAR">Qatari Riyal</option>
      <option value="RON">Romanian Leu</option>
      <option value="RSD">Serbian Dinar</option>
      <option value="RUB">Russian Ruble</option>
      <option value="RWF">Rwandan Franc</option>
      <option value="SAR">Saudi Arabian Riyal</option>
      <option value="SBD">Solomon Islander Dollar</option>
      <option value="SCR">Seychellois Rupee</option>
      <option value="SDG">Sudanese Pound</option>
      <option value="SEK">Swedish Krona</option>
      <option value="SGD">Singapore Dollar</option>
      <option value="SHP">Saint Helenian Pound</option>
      <option value="SLL">Sierra Leonean Leone</option>
      <option value="SOS">Somali Shilling</option>
      <option value="SRD">Surinamese Dollar</option>
      <option value="SSP">South Sudanese Pound</option>
      <option value="STN">Sao Tomean Dobra</option>
      <option value="SYP">Syrian Pound</option>
      <option value="SZL">Swazi Lilangeni</option>
      <option value="THB">Thai Baht</option>
      <option value="TJS">Tajikistani Somoni</option>
      <option value="TMT">Turkmenistani Manat</option>
      <option value="TND">Tunisian Dinar</option>
      <option value="TOP">Tongan Pa'anga</option>
      <option value="TRY">Turkish Lira</option>
      <option value="TTD">Trinidadian Dollar</option>
      <option value="TWD">Taiwan New Dollar</option>
      <option value="TZS">Tanzanian Shilling</option>
      <option value="UAH">Ukrainian Hryvnia</option>
      <option value="UGX">Ugandan Shilling</option>
      <option value="UYU">Uruguayan Peso</option>
      <option value="UZS">Uzbekistani Som</option>
      <option value="VES">Venezuelan Bolívar</option>
      <option value="VND">Vietnamese Dong</option>
      <option value="VUV">Ni-Vanuatu Vatu</option>
      <option value="WST">Samoan Tala</option>
      <option value="XAF">Central African CFA Franc BEAC</option>
      <option value="XCD">East Caribbean Dollar</option>
      <option value="XOF">West African CFA Franc</option>
      <option value="XPF">CFP Franc</option>
      <option value="YER">Yemeni Rial</option>
      <option value="ZAR">South African Rand</option>
      <option value="ZMW">Zambian Kwacha</option>
    </>
  );
};
